/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: spike/csbug-flat/csbug.mjs
 * Command: astryx theme build spike/csbug-flat/csbug.mjs
 * CLI: @astryxdesign/cli@0.4.0
 * Core: @astryxdesign/core@0.4.0
 */

/**
 * csbug theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { csbugTheme } from './csbug';
 *   import './csbug.css';
 */
export const csbugTheme = {
  name: 'csbug',
  __built: true,
  tokens: {
    "--spacing-4": "16px"
  },

};
