/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: spike/csbug-flat/csbug.mjs
 * Command: astryx theme build spike/csbug-flat/csbug.mjs
 * CLI: @astryxdesign/cli@0.4.0
 * Core: @astryxdesign/core@0.4.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const csbugTheme: DefinedTheme;
