/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: spike/queries/queries.mjs
 * Command: astryx theme build spike/queries/queries.mjs
 * CLI: @astryxdesign/cli@0.4.0
 * Core: @astryxdesign/core@0.4.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const queriesTheme: DefinedTheme;
