/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: spike/queries/queries.mjs
 * Command: astryx theme build spike/queries/queries.mjs
 * CLI: @astryxdesign/cli@0.4.0
 * Core: @astryxdesign/core@0.4.0
 */

/**
 * queries theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { queriesTheme } from './queries';
 *   import './queries.css';
 */
export const queriesTheme = {
  name: 'queries',
  __built: true,
  tokens: {
    "--spacing-4": "16px",
    "--color-accent": "#0064E0"
  },

};
