/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: spike/flat/acme.mjs
 * Command: astryx theme build spike/flat/acme.mjs
 * CLI: @astryxdesign/cli@0.4.0
 * Core: @astryxdesign/core@0.4.0
 */

/**
 * acme theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { acmeTheme } from './acme';
 *   import './acme.css';
 */
export const acmeTheme = {
  name: 'acme',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#0064E0, #4599FF)",
    "--color-background-surface": "light-dark(#FFFFFF, #101214)",
    "--radius-container": "12px",
    "--spacing-4": "16px"
  },

};
